.github/release-drafter.yml
.github/workflows/ci.yaml
.github/workflows/dependent-issues.yml
.github/workflows/linked-issue.yml
.github/workflows/pr-labeled.yml
.github/workflows/release-drafter.yml
.github/workflows/semantic-pr.yml
.mergify.yml

build(ci): copy CI configs

---

pom.xml

build(deps): use core version 2.9.0

---

pom.xml

Related to: https://github.com/cryostatio/cryostat/issues/897

chore(core): update core to 2.9.1

---

pom.xml

build(version): bump version to 1.1.0-SNAPSHOT

---

pom.xml

build(version): set version for 1.0.0 release

---

pom.xml

build(version): bump version to 1.0.1-SNAPSHOT

---

.github/workflows/ci.yaml
pom.xml

Fixes: https://github.com/cryostatio/cryostat/issues/973

build(oci): transform image tag to lower case

---

.github/workflows/ci.yaml
.mvn/jvm.config
README.md
pom.xml
src/main/docker/Dockerfile.legacy-jar

chore(pom): update to JDK17

---

.github/workflows/ci.yaml
pom.xml

ci(jdk): build-deps with JDK17

---

pom.xml

Related to: https://github.com/cryostatio/cryostat-core/issues/158

build(core): update core to 2.13.1

---

LICENSE
pom.xml
src/main/java/io/cryostat/reports/Producers.java
src/main/java/io/cryostat/reports/RecordingFormData.java
src/main/java/io/cryostat/reports/ReportResource.java
src/test/java/io/cryostat/NativeReactiveGreetingResourceIT.java
src/test/java/io/cryostat/ReactiveGreetingResourceTest.java
src/test/java/io/cryostat/ReportResourceTest.java

Fixes #48 
Added missing license file and headers (using UPL).

chore(license): add missing license

---

.mergify.yml
src/main/docker/Dockerfile.jvm

Related to https://github.com/cryostatio/cryostat/issues/1118

build(base): update base image

---

pom.xml

Related to: https://github.com/cryostatio/cryostat/issues/1118

build(deps): update core version to 2.14.1

---

pom.xml

Related to cryostatio/cryostat#1118

chore(pom): bump snapshot version

---

pom.xml

Related to cryostatio/cryostat#1118

chore(pom): set version to non-snapshot

---

pom.xml

Related to: https://github.com/cryostatio/cryostat/issues/1302

build(version): set version to 1.1.1

---

pom.xml

Related to: https://github.com/cryostatio/cryostat/issues/1302

build(version): bump version to 1.1.2-SNAPSHOT

---

.github/workflows/ci.yaml

This partially reverts commit 807db1673e9c768ed69baf535fad0d51fe6ab0d3.
Related to #63

ci(image): restore image version parse from pom

---

.mergify.yml
pom.xml

Related to https://github.com/cryostatio/cryostat/issues/1459

build(config): update pom and mergify for 2.3 release

---

pom.xml
src/main/java/io/cryostat/reports/Producers.java
src/main/java/io/cryostat/reports/RecordingFormData.java
src/main/java/io/cryostat/reports/ReportResource.java

chore(quarkus): 'quarkus update' and 'mvn spotless:apply'

---

src/main/docker/Dockerfile.jvm

fix(dockerfile): use JAVA_OPTS_APPEND and do not ExitOnOutOfMemoryError

---

.gitignore
.mergify.yml
pom.xml

Related to cryostatio/cryostat#1695

chore(release): prepare for 2.4.0 release

---

pom.xml

build(deps): upgrade Netty to 4.1.100.Final

---

.github/CODEOWNERS
.github/dependabot.yml
.github/release-drafter.yml

see what @andrewazores suggested: https://github.com/cryostatio/cryostat/issues/1660

ci(dependabot): remove reviewers config

---

pom.xml

This reverts commit f7759d3a17bec533f9a92be4ebc06363dd6d28d6 (#169)

build(deps-dev): downgrade org.jsoup:jsoup from 1.17.1 to 1.16.2

---

.github/workflows/ci.yaml

Related to #198
Related to #202

ci(build): add permissions

---

.github/workflows/ci.yaml

Related to #198
Use caching configuration like https://github.com/cryostatio/cryostat/blob/ece2e2862510b4c0c3f6c75bdd86fbd202c27b73/.github/workflows/ci-build-image.yml#L53

ci(cache): update config

---

.github/workflows/ci.yaml

Related to: #198 
successful workflow: https://github.com/mwangggg/cryostat-reports/actions/runs/7671469218

ci(secrets): add GITHUB_TOKEN authorization to build step

---

src/main/java/io/cryostat/reports/Producers.java
src/main/java/io/cryostat/reports/ReportResource.java

Depends on https://github.com/cryostatio/cryostat-core/pull/336
See also https://github.com/cryostatio/cryostat3/pull/297

fix(analysis): do not use common threadpool if in singlethreaded/singlecore mode

---

.github/workflows/ci.yaml

See https://github.com/cryostatio/cryostat/pull/569

ci(oci): enable parallel builds in OCI format

---

pom.xml
src/main/java/io/cryostat/reports/Producers.java
src/main/java/io/cryostat/reports/ReportResource.java

See https://github.com/cryostatio/cryostat-core/pull/423

chore(libcryostat): clean up to use libcryostat dependency

---

pom.xml

Related to https://github.com/cryostatio/cryostat/issues/364

build(deps): update to Quarkus 3.8 LTS

---

.github/workflows/ci.yaml
README.md
pom.xml
src/main/docker/Dockerfile.jvm
src/main/docker/Dockerfile.legacy-jar

Related to https://github.com/cryostatio/cryostat/issues/364

chore(jdk): upgrade to JDK21

---

pom.xml

- **build(deps): update to Quarkus 3.8 LTS (#265)**
- **build(deps): bump quarkus.platform.version from 3.8.5 to 3.8.6 (#272)**
Related to https://github.com/cryostatio/cryostat/issues/688

chore(quarkus): upgrade to 3.8 LTS

---

pom.xml

See https://github.com/cryostatio/cryostat/issues/548
See https://github.com/cryostatio/cryostat/pull/733

chore(jfr): add quarkus-jfr extension

---

src/main/java/io/cryostat/reports/ReportResource.java
src/main/resources/application.properties

feat(ssl): add controls to ignore storage SSL cert or hostname verification

---

src/main/java/io/cryostat/reports/ReportResource.java

chore(logging): increase error logging

---

src/test/java/io/cryostat/ReportResourceTest.java

See cryostatio/cryostat-core#582

test(rules): adjust expected number of rules to account for new -core rule
